version: '3.8'

networks:
  nest-todo-app-network:
    driver: bridge

services:
  postgres:
    image: postgres:latest
    container_name: nest-todo-app-postgres
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "${DATABASE_PORT}:5432"
    networks:
      - nest-todo-app-network
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
